import React, { useEffect, useState } from 'react';
import { useParams, Link } from 'react-router-dom';
import { ArrowLeft, Calendar, Mountain, Map, BookOpen, Download, CloudRain, ChevronRight, MapPin, TrendingUp, Sparkles } from 'lucide-react';
import { MOCK_FORTS } from '../constants';
import ElevationChart from '../components/ElevationChart';
import FloraSection from '../components/FloraSection';
import BudgetPlanner from '../components/BudgetPlanner';
import GeminiChat from '../components/GeminiChat';
import TrailMap from '../components/TrailMap';
import GeminiTools from '../components/GeminiTools';
import LiveInfoWidget from '../components/LiveInfoWidget';
import { getGeminiTripAdvice } from '../services/geminiService';

const FortDetail: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const fort = MOCK_FORTS.find(f => f.id === id);
  const [activeTab, setActiveTab] = useState<'overview' | 'map' | 'plan' | 'ai'>('overview');
  const [advice, setAdvice] = useState<string>('');

  useEffect(() => {
    window.scrollTo(0, 0);
    if (fort) {
        getGeminiTripAdvice(fort.name, 'current month').then(setAdvice);
    }
  }, [fort]);

  const handlePrint = () => {
    window.print();
  };

  const downloadGPX = () => {
    if (!fort?.trailGeoJSON) {
      alert("No trail data available for this fort.");
      return;
    }

    try {
      const header = `<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<gpx xmlns="http://www.topografix.com/GPX/1/1" creator="Sahyadri Forts Explorer" version="1.1">
  <metadata>
    <name>${fort.name} Trail</name>
    <desc>Generated by Sahyadri Forts Explorer</desc>
  </metadata>`;
      
      let content = '';
      
      fort.trailGeoJSON.features.forEach((feature: any) => {
        if (feature.geometry.type === "LineString") {
          content += `
  <trk>
    <name>${feature.properties.name || fort.name}</name>
    <trkseg>`;
          feature.geometry.coordinates.forEach((coord: number[]) => {
             // GeoJSON is [lng, lat], GPX is lat, lon
             content += `
      <trkpt lat="${coord[1]}" lon="${coord[0]}"></trkpt>`;
          });
          content += `
    </trkseg>
  </trk>`;
        }
      });

      const footer = `
</gpx>`;

      const finalGPX = header + content + footer;
      
      const blob = new Blob([finalGPX], { type: "application/gpx+xml" });
      const url = URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = url;
      link.download = `${fort.id}_trail.gpx`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
    } catch (e) {
      console.error("Failed to generate GPX", e);
      alert("Error generating GPX file.");
    }
  };

  if (!fort) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-stone-50">
        <div className="text-center">
          <h2 className="text-2xl font-serif font-bold text-stone-800">Fort Not Found</h2>
          <Link to="/" className="text-fort-600 hover:text-fort-700 mt-4 inline-flex items-center gap-2 font-medium">
            <ArrowLeft className="w-4 h-4" /> Return to Directory
          </Link>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-stone-50 pb-20 print:bg-white print:pb-0">
      {/* Detail Hero */}
      <div className="relative h-[60vh] min-h-[500px] print:h-auto print:min-h-0 print:py-0">
        <img 
          src={fort.images[0]} 
          alt={fort.name} 
          className="w-full h-full object-cover print:hidden"
        />
        <div className="absolute inset-0 bg-gradient-to-b from-black/60 via-transparent to-stone-50 print:hidden"></div>
        <div className="absolute inset-0 bg-gradient-to-t from-stone-900/80 via-transparent to-transparent print:hidden"></div>
        
        <div className="absolute top-6 left-4 sm:left-8 z-10 print:hidden">
          <Link to="/" className="flex items-center gap-2 text-white/90 hover:text-white transition-colors bg-white/10 backdrop-blur-md border border-white/20 px-4 py-2 rounded-full text-sm font-medium hover:bg-white/20">
            <ArrowLeft className="w-4 h-4" /> Back to Directory
          </Link>
        </div>

        <div className="absolute bottom-0 left-0 right-0 p-6 sm:p-10 max-w-7xl mx-auto w-full z-10 translate-y-12 print:static print:transform-none print:p-0 print:translate-y-0">
          <div className="bg-white rounded-3xl shadow-2xl border border-stone-100 p-6 md:p-8 flex flex-col md:flex-row md:items-start justify-between gap-6 print:shadow-none print:border-none print:p-0 print:mb-6">
            <div className="md:w-2/3 print:w-full">
              <div className="flex items-center gap-3 mb-3 print:mb-2">
                <span className={`px-3 py-1 rounded-full text-xs font-bold uppercase tracking-wider border print:border-stone-900 print:text-black print:bg-transparent ${
                  fort.difficulty === 'Easy' ? 'bg-emerald-50 text-emerald-700 border-emerald-100' :
                  fort.difficulty === 'Moderate' ? 'bg-amber-50 text-amber-700 border-amber-100' :
                  'bg-rose-50 text-rose-700 border-rose-100'
                }`}>
                  {fort.difficulty}
                </span>
                <span className="text-stone-400 text-sm font-serif italic print:text-stone-600">Est. {fort.era}</span>
              </div>
              <h1 className="text-4xl md:text-5xl font-serif font-bold text-stone-900 mb-4 print:text-4xl">{fort.name}</h1>
              <div className="flex flex-wrap gap-4 text-stone-600 text-sm md:text-base print:text-sm print:gap-2">
                <span className="flex items-center gap-1.5 bg-stone-50 px-3 py-1.5 rounded-lg border border-stone-100 print:bg-transparent print:border-none print:p-0"><Map className="w-4 h-4 text-fort-500 print:text-stone-800" /> {fort.region}</span>
                <span className="flex items-center gap-1.5 bg-stone-50 px-3 py-1.5 rounded-lg border border-stone-100 print:bg-transparent print:border-none print:p-0"><Mountain className="w-4 h-4 text-fort-500 print:text-stone-800" /> {fort.elevation}m ASL</span>
                <span className="flex items-center gap-1.5 bg-stone-50 px-3 py-1.5 rounded-lg border border-stone-100 print:bg-transparent print:border-none print:p-0"><Calendar className="w-4 h-4 text-fort-500 print:text-stone-800" /> Best: {fort.bestMonth}</span>
              </div>
            </div>
            
            <div className="flex flex-col gap-3 md:w-1/3 md:items-end print:hidden">
              <button 
                onClick={handlePrint}
                className="w-full md:w-auto bg-stone-900 text-white px-6 py-3 rounded-xl font-semibold text-sm hover:bg-stone-800 transition-all flex items-center justify-center gap-2 shadow-lg active:scale-95"
              >
                <Download className="w-4 h-4" /> Save PDF Guide
              </button>
              <div className="flex items-center gap-1 text-xs text-stone-500">
                <CloudRain className="w-3 h-3" />
                <span>Current Condition: Clear</span>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Spacer for overlapping hero card - hidden in print */}
      <div className="h-24 md:h-12 print:hidden"></div>

      {/* Main Content */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 mt-12 print:mt-4 print:px-0">
        <div className="flex flex-col lg:flex-row gap-8 lg:gap-12 print:block">
          
          {/* Left Column (Content) */}
          <div className="lg:w-2/3 order-2 lg:order-1 print:w-full">
            {/* Tabs - Hidden in Print */}
            <div className="flex p-1 bg-stone-200/50 rounded-xl mb-8 overflow-x-auto border border-stone-200/50 backdrop-blur-sm print:hidden">
              <button 
                onClick={() => setActiveTab('overview')}
                className={`flex-1 px-4 py-2.5 rounded-lg font-medium text-sm transition-all duration-200 whitespace-nowrap ${activeTab === 'overview' ? 'bg-white text-fort-700 shadow-sm ring-1 ring-black/5' : 'text-stone-500 hover:text-stone-700 hover:bg-stone-200/50'}`}
              >
                Overview & History
              </button>
              <button 
                onClick={() => setActiveTab('map')}
                className={`flex-1 px-4 py-2.5 rounded-lg font-medium text-sm transition-all duration-200 whitespace-nowrap ${activeTab === 'map' ? 'bg-white text-fort-700 shadow-sm ring-1 ring-black/5' : 'text-stone-500 hover:text-stone-700 hover:bg-stone-200/50'}`}
              >
                Trail & Map
              </button>
              <button 
                onClick={() => setActiveTab('plan')}
                className={`flex-1 px-4 py-2.5 rounded-lg font-medium text-sm transition-all duration-200 whitespace-nowrap ${activeTab === 'plan' ? 'bg-white text-fort-700 shadow-sm ring-1 ring-black/5' : 'text-stone-500 hover:text-stone-700 hover:bg-stone-200/50'}`}
              >
                Plan Trip
              </button>
               <button 
                onClick={() => setActiveTab('ai')}
                className={`flex-1 px-4 py-2.5 rounded-lg font-medium text-sm transition-all duration-200 whitespace-nowrap flex items-center justify-center gap-1 ${activeTab === 'ai' ? 'bg-white text-purple-700 shadow-sm ring-1 ring-black/5' : 'text-stone-500 hover:text-stone-700 hover:bg-stone-200/50'}`}
              >
                <Sparkles className="w-3.5 h-3.5" /> AI Studio
              </button>
            </div>

            {/* Tab Content */}
            <div className="bg-white rounded-2xl p-6 md:p-8 border border-stone-100 shadow-sm print:shadow-none print:border-none print:p-0">
              {activeTab === 'overview' && (
                <div className="animate-in fade-in slide-in-from-bottom-4 duration-500 space-y-8 print:space-y-6">
                  
                  {/* AI Advice Banner */}
                  <div className="bg-gradient-to-r from-amber-50 to-orange-50 p-5 rounded-xl border border-amber-100/50 flex gap-4 print:bg-white print:border-stone-200">
                     <div className="bg-white p-2 rounded-lg shadow-sm h-fit print:hidden">
                        <CloudRain className="w-5 h-5 text-amber-500" />
                     </div>
                     <div>
                        <h4 className="font-bold text-amber-900 text-sm mb-1 print:text-black">Trip Advisory</h4>
                        <p className="text-amber-800/80 text-sm leading-relaxed print:text-stone-700">"{advice}"</p>
                     </div>
                  </div>

                  <LiveInfoWidget fortName={fort.name} lat={fort.coordinates.lat} lng={fort.coordinates.lng} />

                  <div className="prose prose-stone max-w-none prose-headings:font-serif prose-headings:text-stone-800 prose-p:text-stone-600 prose-p:leading-7 prose-a:text-fort-600 print:prose-p:text-black">
                    <h3 className="text-2xl font-bold">Historical Significance</h3>
                    <p className="first-letter:text-5xl first-letter:font-serif first-letter:font-bold first-letter:text-stone-300 first-letter:mr-3 first-letter:float-left">
                        {fort.description}
                    </p>
                    <p>{fort.history}</p>
                  </div>
                  
                  <hr className="border-stone-100 print:border-stone-200" />

                  <div className="print:hidden">
                    <GeminiChat fortName={fort.name} historyContext={fort.history + " " + fort.description} />
                  </div>
                  
                  <FloraSection plantIds={fort.plants} />

                  <div className="bg-stone-50 rounded-xl p-6 border border-stone-100 print:bg-white print:border-stone-200">
                    <h3 className="font-serif font-bold text-stone-800 mb-4 flex items-center gap-2">
                      <BookOpen className="w-5 h-5 text-fort-600 print:text-stone-800" /> References
                    </h3>
                    <ul className="space-y-3">
                      {fort.references.map((ref, idx) => (
                        <li key={idx} className="flex items-start gap-3 text-sm text-stone-600 bg-white p-3 rounded-lg border border-stone-200 shadow-sm print:shadow-none">
                          <span className="font-bold text-[10px] uppercase tracking-wider bg-stone-100 text-stone-500 px-2 py-1 rounded mt-0.5 print:border print:border-stone-300">{ref.type}</span>
                          <span className="flex-1">{ref.title} <span className="text-stone-400">— {ref.author}</span></span>
                        </li>
                      ))}
                    </ul>
                  </div>
                </div>
              )}

              {activeTab === 'map' && (
                <div className="animate-in fade-in slide-in-from-bottom-4 duration-500 space-y-6">
                  <div className="bg-stone-100 rounded-2xl overflow-hidden h-[500px] border border-stone-200 relative shadow-inner print:border-stone-300">
                    <TrailMap 
                      coordinates={fort.coordinates} 
                      trailGeoJSON={fort.trailGeoJSON} 
                      fortName={fort.name} 
                    />
                  </div>
                  <div className="bg-stone-50 p-6 rounded-xl border border-stone-200 print:bg-white">
                    <h3 className="font-serif font-bold text-stone-800 mb-4 flex items-center gap-2">
                      <TrendingUp className="w-5 h-5 text-fort-600" />
                      Trail Elevation Profile
                    </h3>
                    <ElevationChart data={fort.trailProfile} />
                  </div>
                  <div className="flex flex-wrap gap-4 print:hidden">
                    <button 
                      onClick={downloadGPX}
                      className="flex-1 bg-white border border-stone-200 text-stone-700 px-4 py-3 rounded-xl font-medium hover:bg-stone-50 hover:border-fort-200 hover:text-fort-700 transition-all flex items-center justify-center gap-2 shadow-sm"
                    >
                      <Download className="w-4 h-4" /> Download GPX
                    </button>
                  </div>
                </div>
              )}

              {activeTab === 'plan' && (
                <div className="animate-in fade-in slide-in-from-bottom-4 duration-500">
                  <BudgetPlanner />
                </div>
              )}

              {activeTab === 'ai' && (
                <div className="animate-in fade-in slide-in-from-bottom-4 duration-500">
                  <div className="mb-6">
                     <h3 className="text-xl font-serif font-bold text-stone-800 mb-2">AI Studio</h3>
                     <p className="text-stone-500 text-sm">Use advanced Google AI to analyze photos or generate cinematic videos of {fort.name}.</p>
                  </div>
                  <GeminiTools />
                </div>
              )}
            </div>
          </div>

          {/* Right Column (Sticky Sidebar) - Hidden in Print */}
          <div className="lg:w-1/3 order-1 lg:order-2 space-y-6 print:hidden">
            <div className="sticky top-24 space-y-6">
              <div className="bg-white rounded-2xl shadow-sm border border-stone-100 p-6">
                <h3 className="font-serif font-bold text-lg text-stone-800 mb-6 border-b border-stone-100 pb-2">Quick Facts</h3>
                <div className="space-y-4">
                  <div className="flex justify-between items-center group">
                    <span className="text-stone-500 text-sm flex items-center gap-2"><MapPin className="w-4 h-4 text-stone-300" /> Region</span>
                    <span className="font-medium text-stone-700 group-hover:text-fort-600 transition-colors">{fort.region}</span>
                  </div>
                   <div className="flex justify-between items-center group">
                    <span className="text-stone-500 text-sm flex items-center gap-2"><Calendar className="w-4 h-4 text-stone-300" /> Era</span>
                    <span className="font-medium text-stone-700 text-right w-1/2 group-hover:text-fort-600 transition-colors">{fort.era}</span>
                  </div>
                   <div className="flex justify-between items-center group">
                    <span className="text-stone-500 text-sm flex items-center gap-2"><Mountain className="w-4 h-4 text-stone-300" /> Base</span>
                    <span className="font-medium text-stone-700 group-hover:text-fort-600 transition-colors">{(fort.elevation - 600)}m</span>
                  </div>
                  <div className="flex justify-between items-center group">
                    <span className="text-stone-500 text-sm flex items-center gap-2"><TrendingUp className="w-4 h-4 text-stone-300" /> Difficulty</span>
                    <span className={`font-medium ${fort.difficulty === 'Hard' ? 'text-rose-600' : fort.difficulty === 'Moderate' ? 'text-amber-600' : 'text-emerald-600'}`}>{fort.difficulty}</span>
                  </div>
                </div>
              </div>

               <div className="bg-gradient-to-br from-fort-800 to-fort-900 rounded-2xl shadow-xl text-white p-8 relative overflow-hidden">
                <div className="absolute top-0 right-0 -mr-8 -mt-8 w-32 h-32 bg-white/10 rounded-full blur-2xl"></div>
                <h3 className="font-serif font-bold text-xl mb-3 relative z-10">Support Conservation</h3>
                <p className="text-sm text-fort-100 mb-6 leading-relaxed relative z-10">Help us map more forts and preserve history by contributing GPX files or verified historical data.</p>
                <button className="w-full bg-white text-fort-900 py-3 rounded-xl font-bold text-sm hover:bg-fort-50 transition-colors flex items-center justify-center gap-2 relative z-10">
                  Become a Contributor <ChevronRight className="w-4 h-4" />
                </button>
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>
  );
};

export default FortDetail;